class_names:
  1: mito
labels:
  - 1
thing_list:
  - 1
model: https://zenodo.org/record/6861565/files/MitoNet_v1.pth?download=1
model_quantized: https://zenodo.org/record/6861565/files/MitoNet_v1_quantized.pth?download=1
padding_factor: 16
norms:
  mean: 0.57571
  std: 0.12765
description: Official MitoNet_v1 generalist mitochondrial segmentation model.
FINETUNE:
  criterion: PanopticLoss
  criterion_params:
    ce_weight: 1
    l1_weight: 0.01
    mse_weight: 200
    pr_weight: 1
    top_k_percent: 0.2
  dataset_class: SingleClassInstanceDataset
  dataset_params:
    weight_gamma: 0.7
  engine: PanopticDeepLabEngine
  engine_params:
    confidence_thr: 0.5
    label_divisor: 1000
    nms_kernel: 7
    nms_threshold: 0.1
    stuff_area: 64
    thing_list:
      - 1
    void_label: 0
